libs =
import libs += imgui-platform-glfw%lib{imgui-platform-glfw} 
# import libs += opengl-meta%lib{opengl-gl} imgui-render-opengl3%lib{imgui-render-opengl3} 
import libs += imgui-render-vulkan%lib{imgui-render-vulkan} # vulkan-meta%lib{vulkan}

exe{myapp}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
