libs =
import libs += imgui-platform-glfw%liba{imgui-platform-glfw} imgui-render-opengl3%liba{imgui-render-opengl3}

exe{myapp}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
